# Use the official PostgreSQL image as the base image
FROM postgres:14.2-alpine

# Set environment variables for PostgreSQL
ENV POSTGRES_DB=${POSTGRES_DB}
ENV POSTGRES_USER=${POSTGRES_USER}
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
ENV MAX_CONNECTIONS=500

# Expose PostgreSQL port
EXPOSE 5432